# System checks
include(CheckIncludeFile)
include(CheckFunctionExists)
include(CheckTypeSize)
include(CheckSymbolExists)
include(CheckFunctionExists)
check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
check_function_exists(alarm HAVE_ALARM)
check_function_exists(directio HAVE_DIRECTIO)
check_include_file(errno.h HAVE_ERRNO_H)
check_include_file(fcntl.h HAVE_FCNTL_H)
check_function_exists(fdatasync HAVE_FDATASYNC)
if(CMAKE_COMPILER_IS_GNUCC)
  set(HAVE_FUNC_ATTRIBUTE_FORMAT 1)
  set(HAVE_FUNC_ATTRIBUTE_UNUSED 1)
endif()
check_function_exists(isatty HAVE_ISATTY)
find_library(aio HAVE_LIBAIO)
check_include_file(libgen.h HAVE_LIBGEN_H)
check_include_file(limits.h HAVE_LIMITS_H)
check_include_file(math.h HAVE_MATH_H)
check_symbol_exists(SHM_HUGETLB sys/shm.h HAVE_LARGE_PAGES)
check_function_exists(posix_memalign HAVE_POSIX_MEMALIGN)
check_include_file(pthread.h HAVE_PTHREAD_H)
check_symbol_exists(pthread_cancel pthread.h HAVE_PTHREAD_CANCEL)
check_symbol_exists(pthread_yield pthread.h HAVE_PTHREAD_YIELD)
check_include_file(sched.h HAVE_SCHED_H)
check_function_exists(setvbuf HAVE_SETVBUF)
check_include_file(signal.h HAVE_SIGNAL_H)
check_function_exists(strerror_r HAVE_STRERROR_R)
check_include_file(strings.h HAVE_STRINGS_H)
check_include_file(string.h HAVE_STRING_H)
check_include_file(sys/ipc.h HAVE_SYS_IPC_H)
check_include_file(sys/mman.h HAVE_SYS_MMAN_H)
check_include_file(sys/shm.h HAVE_SYS_SHM_H)
check_include_file(sys/stat.h HAVE_SYS_STAT_H)
check_include_file(thread.h HAVE_THREAD_H)
check_function_exists(thr_setconcurrency HAVE_THR_SETCONCURRENCY)
check_include_file(unistd.h HAVE_UNISTD_H)
check_function_exists(fdatasync HAVE_FDATASYNC)
check_function_exists(memalign HAVE_MEMALIGN)
set(SIZEOF_BOOL 1)
check_type_size(size_t SIZEOF_SIZE_T LANGUAGE C)
check_function_exists(mmap HAVE_MMAP)
check_function_exists(valloc HAVE_VALLOC)
